apiVersion: v1
kind: Secret
metadata:
  name: katpool-secrets
  namespace: katpool
type: Opaque
data:
  TREASURY_PRIVATE_KEY="542f3348a982fa21611afdcc79aec20484190639612e7d09a2c9c2c749ba0d49"
  POSTGRES_USER=postgres
  POSTGRES_PASSWORD=123
  POSTGRES_DB=katpool_mainnet
  POSTGRES_HOSTNAME='katpool-db'
  DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOSTNAME}:5432/${POSTGRES_DB}"
  MONITOR="http://katpool-monitor:9302"
  DEBUG=1
  TELEGRAM_BOT_TOKEN="2093085916:AAHW6ieqHLInWyV7yZVkbfiE2372ezmrQA8"
  DATADOG_SECRET=988d7a4860600e4079e82c42cdbc8160
  DATADOG_LOG_URL=https://http-intake.logs.us5.datadoghq.com/v1/input
  DATABASE_URL_MONITOR="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOSTNAME}:5432/${POSTGRES_DB}"
  DATADOG_SERVICE_NAME=kairat-app-test
  DATADOG_PAYMENT_SERVICE_NAME=kairat-payment-test
  DATADOG_MONITOR_SERVICE_NAME=kairat-monitor-test