apiVersion: v1
kind: Service
metadata:
  name: katpool-app-service
  namespace: katpool
  labels:
    app: katpool-app
spec:
  type: ClusterIP
  ports:
  - port: 1111
    targetPort: 1111
    name: stratum-1111
    protocol: TCP
  - port: 2222
    targetPort: 2222
    name: stratum-2222
    protocol: TCP
  - port: 3333
    targetPort: 3333
    name: stratum-3333
    protocol: TCP
  - port: 4444
    targetPort: 4444
    name: stratum-4444
    protocol: TCP
  - port: 5555
    targetPort: 5555
    name: stratum-5555
    protocol: TCP
  - port: 6666
    targetPort: 6666
    name: stratum-6666
    protocol: TCP
  - port: 7777
    targetPort: 7777
    name: stratum-7777
    protocol: TCP
  - port: 8888
    targetPort: 8888
    name: stratum-8888
    protocol: TCP
  selector:
    app: katpool-app 