apiVersion: v1
kind: Service
metadata:
  name: katpool-service
  namespace: katpool
  labels:
    app: katpool-app
spec:
  type: LoadBalancer
  selector:
    app: katpool-app
  ports:
  - name: stratum-1111
    port: 1111
    targetPort: 1111
  - name: stratum-2222
    port: 2222
    targetPort: 2222
  - name: stratum-3333
    port: 3333
    targetPort: 3333
  - name: stratum-4444
    port: 4444
    targetPort: 4444
  - name: stratum-5555
    port: 5555
    targetPort: 5555
  - name: stratum-6666
    port: 6666
    targetPort: 6666
  - name: stratum-7777
    port: 7777
    targetPort: 7777
  - name: stratum-8888
    port: 8888
    targetPort: 8888
