apiVersion: v1
kind: Service
metadata:
  name: redis-external
  namespace: katpool
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: katpool-db-external
  namespace: katpool
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: katpool-monitor-external
  namespace: katpool
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
  - port: 9301
    targetPort: 9301
    name: monitor-9301
  - port: 9300
    targetPort: 9300
    name: monitor-9300 